# root partition
- name: Create ext4 filesystems on root partition
  community.general.filesystem:
    dev: '{{ fs_partition_root }}'
    fstype: ext4

# boot partition
- name: Create fat32 filesystem on boot partition
  community.general.filesystem:
    dev: '{{ fs_partition_boot }}'
    fstype: vfat
    opts: -F32
